NB_FILTERS = 100
WINDOW_SIZES = [3,4,5]

WORD_EMBED_SIZE = 300
POSITION_EMBED_SIZE = 5
WORD_REPRE_SIZE = WORD_EMBED_SIZE + 2 * POSITION_EMBED_SIZE

SEQUENCE_LEN = 97
MAX_DISTANCE = 61
MIN_DISTANCE = -61
NB_DISTANCES = (MAX_DISTANCE - MIN_DISTANCE + 1) + 1  # 1 for padding

NB_RELATIONS = 9 * 2 + 1  # directed
NB_UND_RELATIONS = 9 + 1  # undirected

LEARNING_RATE = 1e-3
DROPOUT = 0.5

NB_EPOCHS = 200
BATCH_SIZE = 100